import { Rethink_Sans } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';

const rethinkSans = Rethink_Sans({
  variable: '--font-rethink-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rethinkSans.variable} antialiased overflow-x-hidden mx-3 border border-hover-stroke/30 md:border-0`}
      >
        {children}
      </body>
    </html>
  );
}
